package values

const Seed = "seed"
const Host = "host"
const SkipTlsVerify = "skip-tls-verify"
const Timeout = "timeout"
const DryRun = "dry-run"
const MaxSchemaDepth = "max-schema-depth"
const RandomFill = "random-fill"
const BearerToken = "bearer-token"
const CoverageFileDir = "coverage-file-dir"
const MaxMutateLoopCount = "max-mutate-loop-count"
const OutputDir = "output-dir"
const OutputFile = "output-file"
const Enable422Repair = "enable-422-repair"
const EnableStateAwareness = "enable-state-awareness"
const EnableCoverageFeedback = "enable-coverage-feedback"
const Brief = "brief"
const K8sOutputFile = "k8s-output-file"
const TextfmtCoverageFilePath = "textfmt-coverage-file-path"
const KubernetesRootDir = "kubernetes-root-dir"
const StartFunctionKey = "start-function-key"
const GoToolCovdataBinPath = "go-covdata-tool-bin-path"
